version: '3.8'

services:
  collector:
    build:
      context: .
      dockerfile: collector/Dockerfile
    container_name: wigo_collector
    ports:
      - "5000:5000"
      - "514:514"
      - "514:514/udp"
    volumes:
      - ../src/collector:/app/src/collector
      - ../data:/app/data
    environment:
      - TZ=UTC
    restart: unless-stopped
